In [2]:
import json
from pathlib import Path

path = Path(r"C:\Users\Playdata\Desktop\mle-01-p2-team2\전처리\recipes_dish_final.jsonl")

dish_names = []

with path.open("r", encoding="utf-8") as f:
    for line in f:
        if not line.strip():
            continue
        data = json.loads(line)
        name = (data.get("dish") or {}).get("name")
        if name:
            dish_names.append(name)

In [4]:

from collections import Counter

# 문자열과 딕셔너리가 섞인 값을 요리명 문자열로 통일
clean_names = []

for item in dish_names:
    while isinstance(item, dict):
        item = item.get("name")

    if isinstance(item, str) and item.strip():
        clean_names.append(item.strip())

# 요리명별 개수: 많은 순서로 출력
dish_counts = Counter(clean_names)

for name, count in dish_counts.most_common():
    print(f"{name}: {count}")

김치찌개: 42
제육볶음: 33
떡볶이: 32
순두부찌개: 31
미역국: 30
닭볶음탕: 29
어묵볶음: 29
된장찌개: 28
김치찜: 28
멸치볶음: 26
감자조림: 26
수육: 25
볶음밥: 25
계란찜: 24
장조림: 24
두부조림: 23
김밥: 23
잡채: 22
깍두기: 21
오징어볶음: 19
오이무침: 19
부대찌개: 19
갈비찜: 18
비빔국수: 18
무생채: 17
진미채볶음: 17
떡국: 17
돼지갈비찜: 17
김치볶음밥: 17
주먹밥: 16
파김치: 15
감자탕: 15
마늘장아찌: 15
콩나물국: 14
연근조림: 14
고추장찌개: 14
잔치국수: 13
가지볶음: 13
오이소박이: 13
갈치조림: 13
배추겉절이: 13
육개장: 13
열무김치: 13
무말랭이무침: 13
깻잎김치: 12
등갈비찜: 12
된장국: 12
코다리조림: 12
계란말이: 12
배추김치: 12
닭갈비: 11
양파장아찌: 11
감자전: 11
골뱅이무침: 11
김치볶음: 11
샤브샤브: 11
동치미: 11
콩자반: 11
샌드위치: 11
콩나물무침: 10
오므라이스: 10
깻잎장아찌: 10
월남쌈: 10
약밥: 10
동그랑땡: 10
어묵탕: 10
낙지볶음: 10
동태찌개: 10
안동찜닭: 9
카레: 9
소고기무국: 9
전복죽: 9
김치전: 9
삼계탕: 9
불고기: 9
돼지불고기: 9
오이냉국: 9
부추김치: 9
강된장: 9
두부찌개: 9
프렌치토스트: 9
토스트: 9
꽃게탕: 8
마파두부: 8
총각김치: 8
우엉조림: 8
부추무침: 8
찹스테이크: 8
국물떡볶이: 8
밀푀유나베: 8
계란국: 8
짬뽕: 8
비빔밥: 8
숙주볶음: 8
닭개장: 8
애호박전: 8
미역줄기볶음: 7
시금치무침: 7
오징어무국: 7
상추겉절이: 7
가지무침: 7
순대볶음: 7
고사리나물볶음: 7
콩나물불고기: 7
애호박볶음: 7
LA갈비: 7
열무물김치: 7
찜닭: 7
갈비탕: 7
고등어조림: 7
청국장: 7
소시지야채볶음: 7
북어국: 7
마늘쫑볶음: 7
오이지: 7
오이피클: 7
스테이크: 7
굴무침: 7
오징어채볶음: 7
치킨: 7
샐러드: 7
무국: 7
새송이버섯볶음: 7
옥수수: 7
소불고기: 6
감자짜글이: 6
도토리묵무침: 6
표고버섯볶음: 6
육회: 6
감자샐러드: 6
청국장찌개: 6
참치마요덮밥: 6
감자볶음: 6
불고기전골: 6
콘치즈: 6
쫄면: 6
호박볶음: 6
고구마줄기볶음: 6
간장계란밥: 6
수제비: 6
간장게장: 6
꽈리고추 멸치볶음: 6
감자국: 6
단호박죽: 6
무나물: 6
더덕무침: 6
호박전: 6
진미채무침: 6
볶음우동: 6
무쌈말이: 6
아귀찜: 6
육전: 6
고등어무조림: 5
소세지야채볶음: 5
김치비빔국수: 5
볶음김치: 5
메추리알장조림: 5
감자채볶음: 5
계란장조림: 5
콩나물밥: 5
닭곰탕: 5
쭈꾸미볶음: 5
김장김치: 5
고추장아찌: 5
등갈비김치찜: 5
전복버터구이: 5
칠리새우: 5
두부강정: 5
느타리버섯볶음: 5
오삼불고기: 5
두부김치: 5
나박김치: 5
부추겉절이: 5
고사리나물: 5
파래무침: 5
떡꼬치: 5
유부초밥: 5
배추된장국: 5
함박스테이크: 5
식혜: 5
아구찜: 5
어묵국: 5
카레라이스: 5
동태탕: 5
떡만두국: 5
애호박찌개: 5
해물찜: 5
돈까스: 5
호박죽: 5
구운계란: 5
크림파스타: 4
봄동 겉절이: 4
꼬막무침: 4
무조림: 4
감바스 알 아히요: 4
계란장: 4
고구마맛탕: 4
쌈장: 4
부추전: 4
만두국: 4
노각무침: 4
황태국: 4
오이미역냉국: 4
소갈비찜: 4
칼국수: 4
치킨마요덮밥: 4
스팸마요덮밥: 4
닭백숙: 4
무나물볶음: 4
오이지무침: 4
비빔냉면: 4
쪽파김치: 4
알리오올리오: 4
고추장멸치볶음: 4
라볶이: 4
알감자조림: 4
닭한마리: 4
두루치기: 4
만두전골: 4
당근라페: 4
고추잡채: 4
단무지무침: 4
해독주스: 4
탕수육: 4
백김치: 4
연어스테이크: 4
덮밥: 4
보쌈: 4
고구마: 4
간장치킨: 4
더덕구이: 4
해물파전: 4
초고추장: 4
달래장: 4
양배추쌈: 4
콩나물국밥: 4
콩나물잡채: 4
깻잎찜: 4
피자: 4
오이김치: 4
콩국수: 4
땅콩조림: 4
새우튀김: 4
마늘빵: 4
대구탕: 4
가지덮밥: 4
닭죽: 4
김무침: 4
버섯볶음: 4
팽이버섯전: 4
양파볶음: 4
꼬막비빔밥: 4
우럭매운탕: 4
토마토달걀볶음: 4
계란볶음밥: 4
닭강정: 4
건새우볶음: 4
묵은지볶음: 4
소고기장조림: 4
카스테라: 4
봄동겉절이: 4
단호박찜: 4
참치전: 4
문어숙회: 4
비지찌개: 4
사라다빵: 4
김치콩나물국: 3
꽈리고추멸치볶음: 3
김치비지찌개: 3
숙주나물무침: 3
군고구마: 3
차돌박이숙주볶음: 3
소고기뭇국: 3
마파두부덮밥: 3
떡만둣국: 3
갈비구이: 3
알리오올리오 파스타: 3
도라지무침: 3
배추전: 3
가지밥: 3
버섯전골: 3
짜파구리: 3
만두: 3
미역초무침: 3
김치두루치기: 3
감자수제비: 3
열무비빔국수: 3
고등어김치찜: 3
야채죽: 3
콩나물찜: 3
동파육: 3
팥죽: 3
황태채무침: 3
양파덮밥: 3
궁중떡볶이: 3
소시지볶음: 3
차돌박이찜: 3
시래기된장국: 3
비빔만두: 3
오징어국: 3
배추물김치: 3
방울토마토 마리네이드: 3
초밥: 3
짜장: 3
등뼈찜: 3
알탕: 3
삶은 감자: 3
매운탕: 3
가지튀김: 3
매생이굴국: 3
마라탕: 3
미소된장국: 3
청경채볶음: 3
가지나물무침: 3
냉이무침: 3
고등어구이: 3
파절이: 3
돼지불백: 3
과카몰리: 3
두부볶음: 3
간장새우장: 3
양장피: 3
잡채밥: 3
짜글이찌개: 3
코울슬로: 3
열무얼갈이김치: 3
콩나물볶음: 3
닭발볶음: 3
석박지: 3
토란국: 3
롤샌드위치: 3
콩나물찌개: 3
갓김치: 3
굴국: 3
감자찌개: 3
톳나물무침: 3
닭간장조림: 3
깻잎전: 3
장어구이: 3
김치만두: 3
스크램블에그: 3
브로콜리무침: 3
깻잎순볶음: 3
코다리찜: 3
장어탕: 3
대파김치: 3
꽁치무조림: 3
레몬청: 3
오리탕: 3
매실장아찌무침: 3
양파김치: 3
깻잎볶음: 3
계란빵: 3
연포탕: 3
김치국: 3
물김치: 3
리조또: 3
깐풍기: 3
토마토주스: 3
카레볶음밥: 3
편강: 3
냉이된장국: 3
감자튀김: 3
닭도리탕: 3
황태채볶음: 3
치킨무: 3
꼬리곰탕: 3
양배추전: 3
두부구이: 3
미역오이냉국: 3
고구마순볶음: 3
목이버섯볶음: 3
도토리묵사발: 3
쌈밥: 3
마늘쫑고추장무침: 2
감자채전: 2
떡갈비: 2
삶은 계란: 2
토마토 스파게티: 2
양념게장: 2
간장비빔국수: 2
겉절이: 2
오징어초무침: 2
간장찜닭: 2
가지 스테이크: 2
참나물무침: 2
달걀샌드위치: 2
양념치킨: 2
양배추볶음: 2
목살스테이크: 2
굴전: 2
고구마 맛탕: 2
홍합탕: 2
토마토스파게티: 2
오꼬노미야끼: 2
김치: 2
청포묵무침: 2
오이부추무침: 2
돈가스소스: 2
김치수제비: 2
소떡소떡: 2
연어장: 2
마늘쫑무침: 2
미나리무침: 2
삼겹살덮밥: 2
나시고랭: 2
돈가스덮밥: 2
감자계란국: 2
황태해장국: 2
돼지껍데기볶음: 2
소고기볶음: 2
팟타이: 2
김치말이국수: 2
바베큐폭립: 2
파무침: 2
아욱된장국: 2
시금치 된장국: 2
우렁쌈장: 2
탕수만두: 2
연어덮밥: 2
오리불고기: 2
돼지갈비: 2
낙지연포탕: 2
콘샐러드: 2
보쌈무김치: 2
조기매운탕: 2
굴국밥: 2
해파리냉채: 2
닭똥집볶음: 2
파채무침: 2
짜글이: 2
데리야끼소스: 2
메밀소바: 2
마약김밥: 2
두부부침: 2
마녀스프: 2
에그인헬: 2
어리굴젓: 2
배춧국: 2
가자미조림: 2
족발: 2
오징어덮밥: 2
두부스테이크: 2
가지탕수: 2
양파절임: 2
바지락칼국수: 2
새우버터구이: 2
장칼국수: 2
타르타르소스: 2
초코칩쿠키: 2
팽이버섯조림: 2
간장양념장: 2
장아찌: 2
황태콩나물국: 2
도라지볶음: 2
리코타치즈: 2
쪽파무침: 2
국물닭발: 2
달래간장: 2
꽃게찜: 2
몬테크리스토 샌드위치: 2
시금치나물무침: 2
파스타: 2
만두강정: 2
마늘쫑 장아찌: 2
길거리 토스트: 2
양배추찜: 2
명란파스타: 2
탕후루: 2
양배추김치: 2
김치부침개: 2
북엇국: 2
연어 스테이크: 2
메추리알 장조림: 2
두부두루치기: 2
로제파스타: 2
가지나물볶음: 2
햄치즈토스트: 2
명엽채볶음: 2
방풍나물무침: 2
군만두: 2
버섯찌개: 2
에그샌드위치: 2
공심채볶음: 2
고들빼기김치: 2
오이볶음: 2
콩나물비빔밥: 2
닭발: 2
감자샌드위치: 2
콩비지찌개: 2
갈치구이: 2
감바스: 2
우유식빵: 2
연어샐러드: 2
바지락술찜: 2
스파게티: 2
오리백숙: 2
조기조림: 2
달걀죽: 2
단호박빵: 2
취나물무침: 2
웨지감자: 2
봉골레 파스타: 2
삶은 달걀: 2
소고기국: 2
소꼬리찜: 2
스콘: 2
양배추샐러드: 2
명이나물장아찌: 2
스키야키: 2
버섯덮밥: 2
돼지국밥: 2
크림 스파게티: 2
짜장밥: 2
등갈비: 2
도라지나물볶음: 2
고구마순김치: 2
두부전골: 2
양송이수프: 2
어향가지볶음: 2
고갈비: 2
간장국수: 2
북어채무침: 2
돈까스 소스: 2
팬케이크: 2
딸기잼: 2
삼겹살구이: 2
냉라면: 2
도토리묵: 2
얼갈이김치: 2
김장아찌: 2
오믈렛: 2
마늘볶음밥: 2
도토리묵밥: 2
돼지고기 두루치기: 2
비빔당면: 2
육회비빔밥: 2
고추장아찌무침: 2
애플파이: 2
양상추샐러드: 2
곱창전골: 2
배추찜: 2
새우구이: 2
계란후라이: 2
꽈리고추무침: 2
까르보나라: 2
콩나물김치국: 2
소시지강정: 2
돈까스덮밥: 2
들깨탕: 2
가지나물: 2
샐러드 드레싱: 2
족발볶음: 2
양념장: 2
미트볼: 2
마늘종볶음: 2
구운 계란: 2
매실장아찌: 2
청경채 굴소스볶음: 2
매실청: 2
수박화채: 2
미역무침: 2
쌀국수: 2
고추기름: 2
멘보샤: 2
컵케이크: 2
순대전골: 2
취나물볶음: 2
밥피자: 2
비름나물무침: 2
무스비: 2
토마토 주스: 2
나박물김치: 2
달래양념장: 2
감자옹심이: 2
쑥버무리: 2
계란토스트: 2
묵밥: 2
등갈비구이: 2
달걀찜: 2
약식: 2
무밥: 2
누룽지: 2
양배추피클: 2
두부마요네즈: 2
꼬치전: 2
오징어무침: 2
계란탕: 2
연근전: 2
티라미수: 2
대추차: 2
추어탕: 2
고구마 스프: 2
고구마라떼: 2
돼지등뼈찜: 2
소고기덮밥: 2
발사믹드레싱: 2
닭봉조림: 2
또띠아: 2
김치덮밥: 2
파전: 2
감자간장조림: 1
쪽갈비: 1
골뱅이소면무침: 1
불낙지볶음: 1
시금치된장국: 1
만둣국: 1
새송이버섯 간장버터구이: 1
고추장삼겹살: 1
삶은계란: 1
냄비밥: 1
양배추어묵볶음: 1
토마토 달걀볶음: 1
오이탕탕이: 1
목살간장볶음: 1
닭봉간장조림: 1
목살 양념구이: 1
흰죽: 1
오리주물럭: 1
삼겹살: 1
지코바치킨: 1
매운등갈비찜: 1
김치말이찜: 1
오리엔탈 드레싱: 1
쿠키: 1
LA갈비구이: 1
꽈리고추찜: 1
짜장면: 1
보쌈김치: 1
투움바파스타: 1
하이볼: 1
두부짜글이: 1
꽈리고추조림: 1
구운달걀: 1
탕수육소스: 1
에그치즈토스트: 1
버터쿠키: 1
감자스프: 1
고추된장무침: 1
오이고추된장무침: 1
부타동: 1
계란죽: 1
치킨너겟: 1
치킨 데리야끼: 1
오이초무침: 1
달걀밥: 1
메추리알조림: 1
쟁반막국수: 1
두부시금치무침: 1
바질페스토 파스타: 1
우유생크림: 1
신라면투움바 파스타: 1
목살 스테이크: 1
간장파스타: 1
참치계란간장밥: 1
버터구이감자: 1
술빵: 1
시래기들깨된장국: 1
갈릭마요새우: 1
소꼬리곰탕: 1
깻잎부추전: 1
관자 버터구이: 1
감자짜글이찌개: 1
꼬막: 1
대패덮밥: 1
새송이버섯간장버터구이: 1
두부계란국: 1
검은콩자반: 1
뱅쇼: 1
애호박덮밥: 1
규동: 1
양송이버섯덮밥: 1
순두부 계란탕: 1
차슈덮밥: 1
두부덮밥: 1
오야꼬동: 1
매생이 굴국: 1
훈제오리 부추무침: 1
구운 주먹밥: 1
우엉채조림: 1
들기름막국수: 1
뚝배기 불고기: 1
만두버섯전골: 1
꽈리고추볶음: 1
순두부: 1
오징어실채볶음: 1
브로콜리두부무침: 1
오징어간장조림: 1
소고기고추장볶음: 1
깻잎순나물볶음: 1
고추된장박이: 1
삼겹살 간장조림: 1
돼지고기마늘조림: 1
홍어무침: 1
해물탕: 1
달걀조림: 1
파프리카버섯볶음: 1
간장등갈비: 1
도토리묵 양념장: 1
굴배추국: 1
우동: 1
버터갈릭새우: 1
계란감자국: 1
돈부리덮밥: 1
애호박계란국: 1
무물김치: 1
치킨 스테이크: 1
생선조림: 1
사과잼: 1
스팸무스비: 1
마늘조림: 1
유린기: 1
볶음고추장: 1
단호박수프: 1
양배추덮밥: 1
닭튀김: 1
비빔장: 1
오뎅볶음: 1
연두부달걀탕: 1
닭다리살 스테이크: 1
순두부국: 1
사골곰탕: 1
오이토마토무침: 1
고사리육개장: 1
쑥국: 1
느타리버섯전: 1
전복찜: 1
닭고기조림: 1
얼갈이된장국: 1
부추달걀볶음: 1
기름떡볶이: 1
단호박 샐러드: 1
고추장물: 1
죽: 1
수정과: 1
호떡: 1
부추잡채: 1
멸치칼국수: 1
찐고구마: 1
새우탕: 1
마약계란: 1
밤: 1
멸치육수: 1
목살양념구이: 1
고추잎나물무침: 1
알리올리오 볶음밥: 1
청경채겉절이: 1
수플레 팬케이크: 1
단호박스프: 1
양념간장: 1
클럽샌드위치: 1
마늘보쌈: 1
시래기볶음: 1
목살필라프: 1
달래오이무침: 1
이모모찌: 1
달래무침: 1
돼지갈비볶음탕: 1
배추닭국: 1
매쉬드 포테이토: 1
다대기: 1
새송이버섯구이: 1
참치죽: 1
달걀탕: 1
삼겹살볶음: 1
볶음라면: 1
애호박느타리버섯볶음: 1
오이맛살마요무침: 1
소고기산적: 1
소고기죽: 1
이삭토스트: 1
초장: 1
겨자냉채: 1
오이도라지무침: 1
통삼겹살구이: 1
검은콩조림: 1
소고기육전: 1
팽이버섯구이: 1
오니기리: 1
바스크 치즈케이크: 1
팽이버섯덮밥: 1
베이컨말이 주먹밥: 1
오징어찌개: 1
샐러드 파스타: 1
쥐포볶음: 1
팽이버섯볶음: 1
돈까스 김치나베: 1
숙주나물: 1
양념치킨소스: 1
데리야끼 덮밥: 1
찹쌀고추장: 1
토마토소스: 1
양파 간장소스: 1
굴밥: 1
연두부 샐러드: 1
밥버거: 1
마늘종 새우볶음: 1
뼈다귀해장국: 1
오이부추김치: 1
연어 간장조림: 1
대패삼겹살숙주볶음: 1
계란야채죽: 1
초계탕: 1
콩나물탕: 1
간장닭구이: 1
콘치즈 토스트: 1
대패삼겹살 샐러드: 1
비프 스튜: 1
소세지강정: 1
불족발: 1
곰국: 1
감자오믈렛: 1
파절이 소스: 1
마늘쫑장아찌: 1
취나물된장무침: 1
봄동 된장무침: 1
팽이버섯 덮밥: 1
깍두기볶음밥: 1
감자된장국: 1
찹쌀탕수육: 1
김치콩나물국밥: 1
BLT 샌드위치: 1
호박나물볶음: 1
열무 물김치: 1
가지말이 샐러드: 1
애호박부추전: 1
그릭 요거트: 1
주꾸미볶음: 1
열무비빔밥: 1
양배추 계란전: 1
소고기표고버섯덮밥: 1
고추장: 1
녹두빈대떡: 1
팽이버섯 베이컨말이: 1
황태구이: 1
떡간장조림: 1
샐러드드레싱: 1
누룽지백숙: 1
감동란: 1
바지락탕: 1
잣죽: 1
깻잎쌈밥: 1
딸기청: 1
머랭쿠키: 1
연근샐러드: 1
쭈꾸미삼겹살볶음: 1
또띠아토스트: 1
만두볶음밥: 1
양파고추장아찌: 1
고추장불고기: 1
치즈퐁듀: 1
닭가슴살버섯볶음: 1
볶음잡채: 1
닭날개 간장조림: 1
오이크래미연겨자샐러드: 1
달래 양념장: 1
간짜장: 1
닭칼국수: 1
순대국밥: 1
애호박버섯볶음: 1
버터간장계란비빔밥: 1
데리야키 닭고기 구이: 1
감자두부전: 1
고춧잎무침: 1
콩나물볶음밥: 1
라면땅: 1
우유스팀케이크: 1
오이냉채: 1
홍시: 1
마라샹궈: 1
대패삼겹살볶음: 1
김치죽: 1
안심 스테이크: 1
고등어데리야끼구이: 1
총각김치지짐: 1
냉우동샐러드: 1
비트 주스: 1
찹쌀떡: 1
등갈비폭립: 1
비프스튜: 1
곤드레밥: 1
꽈리고추 햄볶음: 1
막걸리: 1
오이장아찌: 1
토란대나물볶음: 1
명태껍질볶음: 1
에그 타르트: 1
탕국: 1
돼지고기볶음: 1
라따뚜이: 1
삼겹살김치말이찜: 1
순대국: 1
버섯들깨탕: 1
목살구이: 1
두부김치계란탕: 1
열무국수: 1
후라이드 치킨: 1
양배추 샐러드: 1
당근사과주스: 1
두부가지구이: 1
냉이된장찌개: 1
전복장: 1
양파계란덮밥: 1
레몬수: 1
잡채덮밥: 1
나초오믈렛: 1
크림스프: 1
돼지고기숙주나물볶음: 1
오징어순대: 1
충무김밥: 1
콩나물밥 양념장: 1
소금빵: 1
오징어튀김: 1
봄동된장국: 1
베이컨숙주볶음: 1
쌀미음: 1
스파게티 소스: 1
머핀: 1
마카로니 샐러드: 1
오이깍두기: 1
닭구이: 1
버섯 깐풍: 1
안심스테이크: 1
무장아찌: 1
백설기: 1
시래기나물볶음: 1
팥찰밥: 1
톳두부무침: 1
동태전: 1
순두부 짜글이: 1
고구마 줄기 김치: 1
닭다리조림: 1
연두부달걀국: 1
데리야끼덮밥: 1
김치짜글이: 1
짜장떡볶이: 1
골뱅이볶음: 1
닭꼬치: 1
팔보채: 1
카프레제: 1
매시드 포테이토: 1
토마토스프: 1
후라이드치킨: 1
치즈감자: 1
나물무침: 1
연어초밥: 1
나폴리탄 스파게티: 1
햄버거: 1
고추장볶음: 1
비빔면: 1
어묵잡채: 1
프렌치 토스트: 1
감자샐러드 샌드위치: 1
가리비찜: 1
굴라시: 1
바게트: 1
돼지고기찌개: 1
시금치 프리타타: 1
김치 양념속: 1
곱창볶음: 1
해파리무침: 1
애호박무침: 1
라면떡볶이: 1
버섯무침: 1
곱창구이: 1
녹두전: 1
바지락 술찜: 1
타코: 1
장어덮밥: 1
과일사라다: 1
삶은 옥수수: 1
고구마튀김: 1
해신탕: 1
에그 샌드위치: 1
계란찜밥: 1
잡쌈: 1
소시지 야채볶음: 1
대파볶음: 1
짜조: 1
고구마빵: 1
김치잡채: 1
소고기말이: 1
동태국: 1
연두부반찬: 1
흑임자드레싱: 1
메밀전병: 1
삼겹살 오븐구이: 1
살사소스: 1
양배추 두부말이찜: 1
가지냉국: 1
훈제오리구이: 1
프렌치 어니언 스프: 1
열무얼갈이물김치: 1
오트밀: 1
부추베이컨말이: 1
돌솥비빔밥: 1
돼지목살구이: 1
배추국: 1
커스터드 푸딩: 1
들깨볶음: 1
매생이전: 1
퀘사디아: 1
청경채 된장무침: 1
비빔두부찌개: 1
드레싱: 1
롤: 1
양배추겉절이: 1
양송이버섯볶음: 1
숙주볶음밥: 1
생선까스: 1
계란초밥: 1
양념꼬막: 1
뚝배기불고기: 1
코다리무조림: 1
바베큐 폭립: 1
호박찌개: 1
라자냐: 1
전복간장조림: 1
계란만두: 1
고추쌈장무침: 1
건새우마늘쫑볶음: 1
짜장라면: 1
머위나물무침: 1
김치어묵국: 1
돌나물무침: 1
텐신항: 1
바질 페스토: 1
간장양념: 1
어묵김밥: 1
생강차: 1
게살볶음밥: 1
일미볶음: 1
생선구이: 1
해물누룽지탕: 1
마카로니콘샐러드: 1
파프리카전: 1
잔치국수 양념장: 1
가츠동: 1
가지구이: 1
고추바사삭 치킨: 1
일본식 카레: 1
호박고지나물볶음: 1
토마토 계란볶음: 1
청경채나물무침: 1
막국수: 1
단호박조림: 1
매운 어묵: 1
로제 떡볶이: 1
시금치나물: 1
아보카도 주스: 1
햄버거 패티: 1
훈제오리볶음: 1
바싹불고기: 1
세발나물무침: 1
곤드레나물밥: 1
명란찌개: 1
시금치달걀볶음: 1
새송이버섯 양배추볶음: 1
깻잎 장아찌: 1
브로콜리 수프: 1
매운족발: 1
어묵 당면볶음: 1
번데기볶음: 1
구절판: 1
폭립: 1
고르곤졸라 피자: 1
마요네즈: 1
코다리강정: 1
새우전: 1
조청: 1
마들렌: 1
선지국: 1
프리타타: 1
명란젓무침: 1
카르보나라: 1
오뎅탕: 1
초계국수: 1
토마토 계란 볶음: 1
김치어묵탕: 1
빠에야: 1
베이컨말이: 1
보쌈조림: 1
만능양념장: 1
무시래기된장지짐: 1
슈가떡: 1
청경채버섯볶음: 1
맛살샐러드: 1
단호박 수프: 1
요거트 드레싱: 1
카레우동: 1
요구르트 젤리: 1
새싹비빔밥: 1
머위대볶음: 1
쌈장찌개: 1
치킨스낵랩: 1
두부전: 1
호두파이: 1
고등어 무조림: 1
산적: 1
알타리김치: 1
오리엔탈드레싱: 1
보리빵: 1
보리굴비: 1
청경채무침: 1
달걀덮밥: 1
대구매운탕: 1
배추무침: 1
도라지오이무침: 1
토스트 핫도그: 1
호두정과: 1
감자 오믈렛: 1
아구탕: 1
어묵전: 1
쇠고기미역국: 1
닭똥집 볶음: 1
LA 갈비: 1
비빔라면: 1
표고버섯전: 1
단호박샐러드: 1
어묵무국: 1
돈까스김치나베: 1
콩장: 1
닭다리 간장조림: 1
옥수수전: 1
크림새우: 1
닭고기 간장조림: 1
수란: 1
닭다리구이: 1
오리엔탈소스: 1
김치콩나물해장국: 1
치즈밥: 1
깻잎두부구이: 1
무초절임: 1
또띠아 피자: 1
마른새우볶음: 1
참깨드레싱: 1
까르보나라 스파게티: 1
버섯장조림: 1
군밤: 1
코다리콩나물찜: 1
곤드레나물볶음: 1
고구마케이크: 1
콩나물냉채: 1
차지키소스: 1
고구마줄기김치: 1
파래초무침: 1
맛간장: 1
밥통카스테라: 1
표고버섯장조림: 1
깐풍만두: 1
도가니탕: 1
미나리전: 1
꿀떡: 1
가자미구이: 1
간장불고기: 1
불닭: 1
콩물: 1
옥수수치즈빵: 1
아귀탕: 1
돼지고기짜글이: 1
상하이 파스타: 1
레몬차: 1
돌미나리초무침: 1
가리비구이: 1
고구마말랭이: 1
오이미역초무침: 1
머위대들깨볶음: 1
바지락 칼국수: 1
감바스 알아히요: 1
미나리 겉절이: 1
모듬전: 1
크레페: 1
매생이떡국: 1
섞박지: 1
곰탕: 1
러스크: 1
오징어젓갈: 1
아보카도덮밥: 1
알밥: 1
보늬밤: 1
치커리무침: 1
콘치즈파이: 1
닭다리살 마늘구이: 1
대패삼겹살말이: 1
두부 두루치기: 1
양배추: 1
삼각주먹밥: 1
양송이버섯 타파스: 1
머위대나물: 1
매운돼지갈비찜: 1
번데기탕: 1
또띠아마늘칩: 1
쿠지라이식 라면: 1
실곤약무침: 1
황태찜: 1
초대리: 1
쭈꾸미 샤브샤브: 1
밥말이: 1
불고기덮밥: 1
브로콜리들깨볶음: 1
마른오징어조림: 1
바나나샐러드: 1
주꾸미 샤브샤브: 1
가지볶음덮밥: 1
볶음밥 그라탕: 1
매생이국: 1
석화찜: 1
스크램블 에그: 1
오코노미야끼: 1
토마토 카프레제: 1
멸치고추장볶음: 1
키위주스: 1
피망볶음: 1
어묵양배추볶음: 1
짬뽕탕: 1
오이롤초밥: 1
컵밥: 1
파기름: 1
뢰스티: 1
쑥개떡: 1
알타리무김치: 1
삼겹살 간장볶음: 1
땡초김밥: 1
양파초절임: 1
치즈볼: 1
달걀볶음밥: 1
메추리알사라다: 1
콩죽: 1
전찌개: 1
주꾸미삼겹살볶음: 1
계란롤볶음밥: 1
오징어찜: 1
연어구이: 1
가또 쇼콜라: 1
된장삼겹살: 1
찹쌀도너츠: 1
고사리볶음: 1
약과: 1
레몬생강청: 1
고추다대기: 1
생태찌개: 1
골뱅이소면: 1
고추멸치조림: 1
치즈케이크: 1
핫케이크: 1
간장달걀밥: 1
차돌박이 숙주찜: 1
수박주스: 1
달걀사라다빵: 1
배추된장무침: 1
멸치국수: 1
항정살덮밥: 1
오만둥이 콩나물찜: 1
오이들깨볶음: 1
해물짬뽕탕: 1
버섯채소구이: 1
오이고추 된장무침: 1
오징어채무침: 1
연어무쌈말이: 1
닭똥집튀김: 1
깻잎나물무침: 1
삼겹살조림: 1
계란말이김밥: 1
닭볶음: 1
오이부추겉절이: 1
불고기버섯전골: 1
오리훈제 고추장볶음: 1
참치쌈장: 1
총각김치볶음: 1
냉우동: 1
버터구이오징어: 1
초코머핀: 1
초콜릿: 1
만두피: 1
매생이굴떡국: 1
봉골레 스파게티: 1
고등어김치조림: 1
뉴욕치즈케이크: 1
매실주: 1
만두밥: 1
마늘쫑조림: 1
카프레제 샐러드: 1
꽃게무침: 1
고구마 사과 샐러드: 1
온메밀국수: 1
얼갈이배추겉절이: 1
통삼겹살 오븐구이: 1
가라아게: 1
에그롤 토스트: 1
콩나물어묵볶음: 1
문어조림: 1
고추장 삼겹살: 1
푸팟퐁커리: 1
고구마 말랭이: 1
고추장감자찌개: 1
도다리쑥국: 1
교촌치킨: 1
닭가슴살냉채: 1
샹그리아: 1
콘치즈토스트: 1
닭조림: 1
김치우동: 1
닭가슴살사과샐러드: 1
로스트치킨윙: 1
고추전: 1
모닝빵 샌드위치: 1
감자멸치볶음: 1
콩비지전: 1
마약달걀: 1
새우 콩나물찜: 1
마늘소스: 1
황태무국: 1
새우젓무침: 1
빵가루: 1
된장라면: 1
두릅무침: 1
김치밥: 1
고추장진미채볶음: 1
오이롤: 1
등갈비조림: 1
우거지 갈비탕: 1
연근튀김: 1
풋고추전: 1
막걸리 식초: 1
얼갈이열무김치: 1
데리야끼스테이크덮밥: 1
크래미전: 1
간장연어장: 1
만능맛간장: 1
두릅장아찌: 1
콩나물어묵잡채: 1
짬뽕라면: 1
참치 스테이크: 1
멸치주먹밥: 1
꼬막찜: 1
양미리조림: 1
맥적: 1
어묵꼬치: 1
양갈비 스테이크: 1
간장떡볶이: 1
버터링 쿠키: 1
생선찜: 1
호박느타리버섯볶음: 1
마른오징어 간장조림: 1
닭날개 오븐구이: 1
부침개 양념장: 1
산적꼬치전: 1
약고추장: 1
김치국밥: 1
야채튀김: 1
미역나물무침: 1
톳무침: 1
새우젓두부찌개: 1
삼색소보로덮밥: 1
갈치 무조림: 1
돼지껍데기: 1
참치밥전: 1
국수: 1
미역줄기무침: 1
상추꽃밥: 1
양파 피클: 1
양배추롤: 1
베이컨간장말이밥: 1
콩나물두부조림: 1
카페라떼: 1
육포: 1
에그베네딕트: 1
라이스페이퍼 찬밥말이: 1
아보카도 토마토 샐러드: 1
옥수수피자: 1
비빔메밀국수: 1
양파볶음비빔밥: 1
길거리토스트: 1
새우소금구이: 1
물회: 1
소보로동: 1
인절미: 1
수육전골: 1
블루베리잼: 1
마늘종장아찌: 1
돼지고기 생강구이: 1
병어조림: 1
죽순볶음: 1
꼴뚜기볶음: 1
파베초콜릿: 1
몬테크리스토: 1
고등어강된장: 1
쑥갓무침: 1
노가리조림: 1
포기김치: 1
탕평채: 1
고추참치: 1
계란 토마토 볶음: 1
양배추샌드위치: 1
오징어숙회: 1
산적꼬치: 1
샥슈카: 1
등갈비양념구이: 1
유산슬: 1
소세지찌개: 1
피클: 1
고구마쿠키: 1
콥샐러드: 1
삼치조림: 1
라면: 1
사과롤샌드위치: 1
카나페: 1
산적구이: 1
들깨강정: 1
장조림버터비빔밥: 1
참나물겉절이: 1
늙은호박전: 1
콩나물부추무침: 1
새우머리버터구이: 1
가오리찜: 1
굴: 1
치즈: 1
낫또: 1
묵사발: 1
골빔면: 1
햄두부전: 1
솥밥: 1
두부찜: 1
마른오징어: 1
들깨버섯볶음: 1
통삼겹구이: 1
감자떡: 1
생강청: 1
야채스프: 1
쉬림프로제파스타: 1
당근볶음: 1
우뭇가사리 무침: 1
시래기 된장지짐: 1
즉석떡볶이: 1
당근케이크: 1
김부각: 1
김자반무침: 1
베이글: 1
와플: 1
닭가슴살 샐러드: 1
오리무쌈말이: 1
골뱅이소면물회: 1
당면볶음덮밥: 1
참치찌개: 1
비빔칼국수: 1
오징어도라지무침: 1

In [7]:
import pandas as pd

dish_summary = (
    pd.Series(clean_names, name="dish")
    .value_counts()
    .rename_axis("dish")
    .reset_index(name="count")
)

with pd.option_context("display.max_rows", None):
    display(dish_summary)

              dish  count
0             김치찌개     42
1             제육볶음     33
2              떡볶이     32
3            순두부찌개     31
4              미역국     30
5             닭볶음탕     29
6             어묵볶음     29
7             된장찌개     28
8              김치찜     28
9             감자조림     26
10            멸치볶음     26
11              수육     25
12             볶음밥     25
13             장조림     24
14             계란찜     24
15            두부조림     23
16              김밥     23
17              잡채     22
18             깍두기     21
19           오징어볶음     19
20            오이무침     19
21            부대찌개     19
22            비빔국수     18
23             갈비찜     18
24           돼지갈비찜     17
25           김치볶음밥     17
26           진미채볶음     17
27             무생채     17
28              떡국     17
29             주먹밥     16
30             감자탕     15
31             파김치     15
32           마늘장아찌     15
33           고추장찌개     14
34            연근조림     14
35            콩나물국     14
36            잔치국수     13
37            열무김치     13
38             육개장     13
39          무말랭이무침     13
40           배추겉절이     13
41           오이소박이     13
42            갈치조림     13
43            가지볶음     13
44           코다리조림     12
45            계란말이     12
46            등갈비찜     12
47            배추김치     12
48            깻잎김치     12
49             된장국     12
50             감자전     11
51           양파장아찌     11
52            샌드위치     11
53             닭갈비     11
54            샤브샤브     11
55             콩자반     11
56            김치볶음     11
57           골뱅이무침     11
58             동치미     11
59            동태찌개     10
60             어묵탕     10
61              약밥     10
62            낙지볶음     10
63           오므라이스     10
64             월남쌈     10
65            동그랑땡     10
66           콩나물무침     10
67           깻잎장아찌     10
68            두부찌개      9
69          프렌치토스트      9
70           돼지불고기      9
71             불고기      9
72           소고기무국      9
73             전복죽      9
74              카레      9
75             토스트      9
76            부추김치      9
77             강된장      9
78            안동찜닭      9
79             삼계탕      9
80             김치전      9
81            오이냉국      9
82             꽃게탕      8
83            총각김치      8
84             닭개장      8
85           밀푀유나베      8
86             계란국      8
87             비빔밥      8
88            마파두부      8
89           국물떡볶이      8
90            부추무침      8
91              짬뽕      8
92            애호박전      8
93           찹스테이크      8
94            숙주볶음      8
95            우엉조림      8
96            가지무침      7
97            스테이크      7
98           애호박볶음      7
99         고사리나물볶음      7
100           순대볶음      7
101            북어국      7
102            청국장      7
103            오이지      7
104             찜닭      7
105          고등어조림      7
106           LA갈비      7
107        소시지야채볶음      7
108            옥수수      7
109            갈비탕      7
110          마늘쫑볶음      7
111          상추겉절이      7
112            굴무침      7
113             무국      7
114          시금치무침      7
115             치킨      7
116          오징어무국      7
117         미역줄기볶음      7
118        새송이버섯볶음      7
119         콩나물불고기      7
120          열무물김치      7
121            샐러드      7
122         오징어채볶음      7
123           오이피클      7
124          감자짜글이      6
125            무나물      6
126        고구마줄기볶음      6
127           호박볶음      6
128          불고기전골      6
129           소불고기      6
130           간장게장      6
131            수제비      6
132           감자볶음      6
133             쫄면      6
134          감자샐러드      6
135           볶음우동      6
136      꽈리고추 멸치볶음      6
137            콘치즈      6
138          간장계란밥      6
139             육전      6
140         표고버섯볶음      6
141         도토리묵무침      6
142           더덕무침      6
143            감자국      6
144           무쌈말이      6
145         참치마요덮밥      6
146          진미채무침      6
147            호박전      6
148          청국장찌개      6
149             육회      6
150           단호박죽      6
151            아귀찜      6
152           볶음김치      5
153          계란장조림      5
154        메추리알장조림      5
155          카레라이스      5
156           떡만두국      5
157            동태탕      5
158          쭈꾸미볶음      5
159            닭곰탕      5
160          고추장아찌      5
161            어묵국      5
162            아구찜      5
163          애호박찌개      5
164           콩나물밥      5
165          감자채볶음      5
166           유부초밥      5
167            해물찜      5
168           구운계란      5
169         등갈비김치찜      5
170             식혜      5
171           김장김치      5
172         함박스테이크      5
173           칠리새우      5
174          부추겉절이      5
175          고사리나물      5
176           파래무침      5
177            돈까스      5
178          배추된장국      5
179            떡꼬치      5
180          오삼불고기      5
181         전복버터구이      5
182            호박죽      5
183           두부김치      5
184        느타리버섯볶음      5
185           두부강정      5
186           나박김치      5
187         고등어무조림      5
188        소세지야채볶음      5
189         김치비빔국수      5
190          크림파스타      4
191           초고추장      4
192           비빔냉면      4
193          오이지무침      4
194           문어숙회      4
195            참치전      4
196        고추장멸치볶음      4
197         알리오올리오      4
198           사라다빵      4
199           두루치기      4
200           닭한마리      4
201           쪽파김치      4
202           당근라페      4
203         소고기장조림      4
204           카스테라      4
205           만두전골      4
206           고추잡채      4
207            칼국수      4
208         스팸마요덮밥      4
209          봄동겉절이      4
210           단호박찜      4
211            라볶이      4
212          알감자조림      4
213           비지찌개      4
214            닭백숙      4
215          무나물볶음      4
216         치킨마요덮밥      4
217             보쌈      4
218           가지덮밥      4
219            계란장      4
220            마늘빵      4
221            대구탕      4
222            고구마      4
223            백김치      4
224         오이미역냉국      4
225           간장치킨      4
226             닭죽      4
227            김무침      4
228         연어스테이크      4
229           소갈비찜      4
230          꼬막비빔밥      4
231           양파볶음      4
232          팽이버섯전      4
233           버섯볶음      4
234            탕수육      4
235           해독주스      4
236          단무지무침      4
237          우럭매운탕      4
238        토마토달걀볶음      4
239          계란볶음밥      4
240            만두국      4
241           노각무침      4
242            황태국      4
243          묵은지볶음      4
244            닭강정      4
245          건새우볶음      4
246            콩국수      4
247           해물파전      4
248      감바스 알 아히요      4
249           땅콩조림      4
250          고구마맛탕      4
251            무조림      4
252           더덕구이      4
253           오이김치      4
254            달래장      4
255           양배추쌈      4
256            깻잎찜      4
257         봄동 겉절이      4
258           꼬막무침      4
259          콩나물잡채      4
260             피자      4
261          콩나물국밥      4
262           새우튀김      4
263             덮밥      4
264             쌈장      4
265            부추전      4
266        매실장아찌무침      3
267          꽁치무조림      3
268            레몬청      3
269            장어탕      3
270           대파김치      3
271          깻잎순볶음      3
272           코다리찜      3
273           깻잎볶음      3
274          감자수제비      3
275            가지밥      3
276           버섯전골      3
277            오리탕      3
278          닭간장조림      3
279            깻잎전      3
280            동파육      3
281           장어구이      3
282         고등어김치찜      3
283            야채죽      3
284         열무비빔국수      3
285           양파김치      3
286          미역초무침      3
287         김치두루치기      3
288             만두      3
289         브로콜리무침      3
290         스크램블에그      3
291           김치만두      3
292           콩나물찜      3
293            배추전      3
294           짜파구리      3
295           양파덮밥      3
296           닭발볶음      3
297            석박지      3
298          콩나물찌개      3
299            계란빵      3
300          롤샌드위치      3
301          콩나물볶음      3
302            물김치      3
303            리조또      3
304            깐풍기      3
305          토마토주스      3
306          황태채무침      3
307           감자찌개      3
308            갓김치      3
309          톳나물무침      3
310         마파두부덮밥      3
311          간장새우장      3
312            잡채밥      3
313            양장피      3
314          짜글이찌개      3
315           코울슬로      3
316          소시지볶음      3
317          궁중떡볶이      3
318           비빔만두      3
319         시래기된장국      3
320          차돌박이찜      3
321           닭도리탕      3
322           감자튀김      3
323          냉이된장국      3
324             편강      3
325          카레볶음밥      3
326        열무얼갈이김치      3
327           떡만둣국      3
328           갈비구이      3
329     알리오올리오 파스타      3
330             팥죽      3
331             굴국      3
332            김치국      3
333            연포탕      3
334            토란국      3
335           돼지불백      3
336            파절이      3
337           과카몰리      3
338       차돌박이숙주볶음      3
339          소고기뭇국      3
340           두부볶음      3
341          도라지무침      3
342           군고구마      3
343          황태채볶음      3
344            치킨무      3
345           꼬리곰탕      3
346       꽈리고추멸치볶음      3
347           양배추전      3
348           냉이무침      3
349         가지나물무침      3
350          고등어구이      3
351           오징어국      3
352            마라탕      3
353          배추물김치      3
354             초밥      3
355          미소된장국      3
356          청경채볶음      3
357    방울토마토 마리네이드      3
358         고구마순볶음      3
359         목이버섯볶음      3
360         김치콩나물국      3
361         미역오이냉국      3
362         김치비지찌개      3
363         도토리묵사발      3
364         숙주나물무침      3
365           두부구이      3
366           가지튀김      3
367          매생이굴국      3
368          삶은 감자      3
369             알탕      3
370             짜장      3
371            등뼈찜      3
372            매운탕      3
373             쌈밥      3
374           달래간장      2
375          콩비지찌개      2
376           팬케이크      2
377            오믈렛      2
378           국물닭발      2
379         달걀샌드위치      2
380           쪽파무침      2
381         감자샌드위치      2
382         콩나물김치국      2
383            고갈비      2
384        도라지나물볶음      2
385           양배추찜      2
386        길거리 토스트      2
387           나시고랭      2
388          삼겹살덮밥      2
389         어향가지볶음      2
390          미나리무침      2
391          육회비빔밥      2
392          연어샐러드      2
393           연어덮밥      2
394          마늘쫑무침      2
395           탕수만두      2
396            연어장      2
397           김장아찌      2
398        마늘쫑 장아찌      2
399          보쌈무김치      2
400            등갈비      2
401           콘샐러드      2
402       메추리알 장조림      2
403        연어 스테이크      2
404          낙지연포탕      2
405           돼지갈비      2
406            겉절이      2
407         돈까스 소스      2
408         데리야끼소스      2
409            짜글이      2
410          까르보나라      2
411           파채무침      2
412          닭똥집볶음      2
413          해파리냉채      2
414            굴국밥      2
415          돈까스덮밥      2
416          조기매운탕      2
417            짜장밥      2
418            북엇국      2
419          김치부침개      2
420          오리불고기      2
421          양배추김치      2
422           마약김밥      2
423         꽈리고추무침      2
424           메밀소바      2
425        크림 스파게티      2
426         양상추샐러드      2
427            탕후루      2
428           우렁쌈장      2
429        시금치 된장국      2
430          참나물무침      2
431          명란파스타      2
432          아욱된장국      2
433           간장찜닭      2
434            파무침      2
435         두부두루치기      2
436           돼지국밥      2
437           조기조림      2
438           오리백숙      2
439          바베큐폭립      2
440         김치말이국수      2
441        가지 스테이크      2
442            팟타이      2
443          소고기볶음      2
444          양송이수프      2
445           소떡소떡      2
446          김치수제비      2
447        돼지껍데기볶음      2
448           에그인헬      2
449          계란후라이      2
450           마녀스프      2
451          양배추볶음      2
452           두부전골      2
453           두부부침      2
454          얼갈이김치      2
455           새우구이      2
456         두부스테이크      2
457          오징어덮밥      2
458          돈가스소스      2
459         오이부추무침      2
460             족발      2
461           애플파이      2
462           스파게티      2
463           도토리묵      2
464           비빔당면      2
465          바지락술찜      2
466          가자미조림      2
467            배춧국      2
468           어리굴젓      2
469          북어채무침      2
470           소꼬리찜      2
471         방풍나물무침      2
472           소고기국      2
473          소시지강정      2
474          명엽채볶음      2
475         햄치즈토스트      2
476         가지나물볶음      2
477           장칼국수      2
478         새우버터구이      2
479          로제파스타      2
480          삶은 달걀      2
481      돼지고기 두루치기      2
482         바지락칼국수      2
483        봉골레 파스타      2
484           양파절임      2
485           가지탕수      2
486           오이볶음      2
487           웨지감자      2
488         고들빼기김치      2
489          취나물무침      2
490          공심채볶음      2
491            냉라면      2
492         오징어초무침      2
493          황태해장국      2
494          도토리묵밥      2
495           단호박빵      2
496         고구마순김치      2
497            달걀죽      2
498         에그샌드위치      2
499           간장국수      2
500           버섯찌개      2
501         타르타르소스      2
502            군만두      2
503        고추장아찌무침      2
504             닭발      2
505            배추찜      2
506         팽이버섯조림      2
507          청포묵무침      2
508          삼겹살구이      2
509           곱창전골      2
510          감자계란국      2
511             김치      2
512          돈가스덮밥      2
513          초코칩쿠키      2
514           버섯덮밥      2
515         오꼬노미야끼      2
516        토마토스파게티      2
517            홍합탕      2
518           스키야키      2
519           양념치킨      2
520          리코타치즈      2
521        명이나물장아찌      2
522         콩나물비빔밥      2
523          도라지볶음      2
524         황태콩나물국      2
525            딸기잼      2
526           우유식빵      2
527            장아찌      2
528          마늘볶음밥      2
529          간장양념장      2
530            감바스      2
531         고구마 맛탕      2
532         양배추샐러드      2
533             굴전      2
534         목살스테이크      2
535           만두강정      2
536             스콘      2
537            파스타      2
538        시금치나물무침      2
539           갈치구이      2
540    몬테크리스토 샌드위치      2
541            꽃게찜      2
542            들깨탕      2
543           족발볶음      2
544        샐러드 드레싱      2
545           가지나물      2
546            미트볼      2
547       토마토 스파게티      2
548         간장비빔국수      2
549           양념게장      2
550            양념장      2
551          마늘종볶음      2
552      청경채 굴소스볶음      2
553          매실장아찌      2
554          구운 계란      2
555           고추기름      2
556            쌀국수      2
557           미역무침      2
558           수박화채      2
559            매실청      2
560           순대전골      2
561          삶은 계란      2
562            떡갈비      2
563           컵케이크      2
564            멘보샤      2
565         비름나물무침      2
566            밥피자      2
567          취나물볶음      2
568          달래양념장      2
569          나박물김치      2
570         토마토 주스      2
571            무스비      2
572          감자옹심이      2
573           쑥버무리      2
574          계란토스트      2
575           감자채전      2
576       마늘쫑고추장무침      2
577             묵밥      2
578          등갈비구이      2
579             약식      2
580            달걀찜      2
581             무밥      2
582          양배추피클      2
583            누룽지      2
584          오징어무침      2
585            꼬치전      2
586         두부마요네즈      2
587            계란탕      2
588            연근전      2
589            대추차      2
590           티라미수      2
591            추어탕      2
592          고구마라떼      2
593         고구마 스프      2
594           닭봉조림      2
595         발사믹드레싱      2
596          소고기덮밥      2
597          돼지등뼈찜      2
598            또띠아      2
599           김치덮밥      2
600             파전      2
601            해물탕      1
602           홍어무침      1
603       돼지고기마늘조림      1
604          볶음고추장      1
605            유린기      1
606           마늘조림      1
607          스팸무스비      1
608            사과잼      1
609           생선조림      1
610        치킨 스테이크      1
611           무물김치      1
612         애호박계란국      1
613          돈부리덮밥      1
614          계란감자국      1
615      닭다리살 스테이크      1
616         연두부달걀탕      1
617           오뎅볶음      1
618            비빔장      1
619            닭튀김      1
620         버터구이감자      1
621        참치계란간장밥      1
622          간장파스타      1
623        목살 스테이크      1
624     신라면투움바 파스타      1
625          우유생크림      1
626      바질페스토 파스타      1
627          양배추덮밥      1
628          단호박수프      1
629          닭고기조림      1
630            전복찜      1
631         느타리버섯전      1
632             쑥국      1
633        두부시금치무침      1
634          쟁반막국수      1
635         메추리알조림      1
636            달걀밥      1
637         고사리육개장      1
638        오이토마토무침      1
639           사골곰탕      1
640           순두부국      1
641           찐고구마      1
642          멸치칼국수      1
643           부추잡채      1
644             호떡      1
645            수정과      1
646              죽      1
647           고추장물      1
648        단호박 샐러드      1
649          기름떡볶이      1
650         부추달걀볶음      1
651         얼갈이된장국      1
652         청경채겉절이      1
653      알리올리오 볶음밥      1
654        고추잎나물무침      1
655         목살양념구이      1
656           멸치육수      1
657              밤      1
658           마약계란      1
659            새우탕      1
660         클럽샌드위치      1
661           양념간장      1
662          단호박스프      1
663          오이초무침      1
664        치킨 데리야끼      1
665           치킨너겟      1
666            계란죽      1
667       수플레 팬케이크      1
668       매쉬드 포테이토      1
669           배추닭국      1
670        돼지갈비볶음탕      1
671           달래무침      1
672           이모모찌      1
673         달래오이무침      1
674          목살필라프      1
675          시래기볶음      1
676           마늘보쌈      1
677            참치죽      1
678        새송이버섯구이      1
679            다대기      1
680            부타동      1
681       오이고추된장무침      1
682         고추된장무침      1
683           감자스프      1
684           버터쿠키      1
685        에그치즈토스트      1
686          탕수육소스      1
687           구운달걀      1
688        오이도라지무침      1
689           겨자냉채      1
690             초장      1
691          이삭토스트      1
692           소고기죽      1
693          소고기산적      1
694       오이맛살마요무침      1
695     애호박느타리버섯볶음      1
696           볶음라면      1
697          삼겹살볶음      1
698            달걀탕      1
699        샐러드 파스타      1
700          오징어찌개      1
701      베이컨말이 주먹밥      1
702         팽이버섯덮밥      1
703      바스크 치즈케이크      1
704           오니기리      1
705         팽이버섯구이      1
706          소고기육전      1
707          검은콩조림      1
708         통삼겹살구이      1
709       돈까스 김치나베      1
710         팽이버섯볶음      1
711         꽈리고추조림      1
712          두부짜글이      1
713            하이볼      1
714         투움바파스타      1
715           보쌈김치      1
716            짜장면      1
717           쥐포볶음      1
718             굴밥      1
719          꽈리고추찜      1
720        양파 간장소스      1
721          토마토소스      1
722          찹쌀고추장      1
723        데리야끼 덮밥      1
724         양념치킨소스      1
725           숙주나물      1
726          소세지강정      1
727          비프 스튜      1
728      대패삼겹살 샐러드      1
729        콘치즈 토스트      1
730          간장닭구이      1
731           콩나물탕      1
732            초계탕      1
733          계란야채죽      1
734      대패삼겹살숙주볶음      1
735        연어 간장조림      1
736         오이부추김치      1
737         뼈다귀해장국      1
738       마늘종 새우볶음      1
739            밥버거      1
740        연두부 샐러드      1
741         깍두기볶음밥      1
742        팽이버섯 덮밥      1
743        봄동 된장무침      1
744         LA갈비구이      1
745             쿠키      1
746        취나물된장무침      1
747         마늘쫑장아찌      1
748         파절이 소스      1
749          감자오믈렛      1
750             곰국      1
751            불족발      1
752         애호박부추전      1
753       가지말이 샐러드      1
754         열무 물김치      1
755         호박나물볶음      1
756       BLT 샌드위치      1
757        김치콩나물국밥      1
758          찹쌀탕수육      1
759          감자된장국      1
760         샐러드드레싱      1
761          떡간장조림      1
762           황태구이      1
763     팽이버섯 베이컨말이      1
764          녹두빈대떡      1
765            고추장      1
766      소고기표고버섯덮밥      1
767        양배추 계란전      1

In [8]:
dish_summary

        dish  count
0       김치찌개     42
1       제육볶음     33
2        떡볶이     32
3      순두부찌개     31
4        미역국     30
...      ...    ...
1441    야채스프      1
1442     생강청      1
1443     감자떡      1
1444   통삼겹구이      1
1445  들깨버섯볶음      1

[1446 rows x 2 columns]